//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bamboo.Sharp.Api.Specs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bamboo.Sharp.Api.Specs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;expand&quot;: &quot;projects&quot;,
        ///    &quot;link&quot;: {
        ///        &quot;href&quot;: &quot;http://192.168.56.1:8085/rest/api/latest/project&quot;,
        ///        &quot;rel&quot;: &quot;self&quot;
        ///    },
        ///    &quot;projects&quot;: {
        ///        &quot;size&quot;: 2,
        ///        &quot;expand&quot;: &quot;project&quot;,
        ///        &quot;start-index&quot;: 0,
        ///        &quot;max-result&quot;: 2,
        ///        &quot;project&quot;: [
        ///            {
        ///                &quot;expand&quot;: &quot;plans&quot;,
        ///                &quot;key&quot;: &quot;CMSBUIL&quot;,
        ///                &quot;name&quot;: &quot;Cms.Builder.Api&quot;,
        ///                &quot;link&quot;: {
        ///                    &quot;href&quot;: &quot;http://192.168.56.1:8085/rest/api/lat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectsJson {
            get {
                return ResourceManager.GetString("ProjectsJson", resourceCulture);
            }
        }
    }
}
